<?xml version="1.0"?>
<robot name="camera_velodyne" xmlns:xacro="http://ros.org/wiki/xacro">
	<!-- constants for robot dimentions  -->
	<xacro:property name="pi" value="3.141592"/>
	<xacro:property name="velodyne_height" value="1.35"/>
	<xacro:property name="camera_height" value="1.10"/>
	<xacro:property name="camera_depth" value="0.35"/>

	<xacro:property name="velodyne_base_length" value="0.0586740"/>
	<xacro:property name="velodyne_diameter" value="0.0853440"/>
	<xacro:property name="velodyne_top_length" value="0.0835714"/>
	<xacro:property name="velodyne_top_center" value="0.0069204"/>
	<xacro:property name="velodyne_laser_depth" value="0.03475311"/>
	<xacro:property name="velodyne_laser_height" value="0.0404979"/>
	<xacro:property name="velodyne_laser_width" value="0.0468099"/>

	<!-- inertial for box -->
	<xacro:macro 
		name="default_box_inertial" 
		params="mass depth width height x_offset y_offset z_offset">
		<inertial>
			<origin xyz="${x_offset} ${y_offset} ${z_offset}" rpy="0 0 0"/>
			<mass value="${mass}"/>
			<inertia 
				ixx="1.0" ixy="0.0" ixz="0.0" 
				iyy="1.0" iyz="0.0" 
				izz="1.0"/>
		</inertial>
	</xacro:macro>

	<!-- inertial for cylinder -->
	<xacro:macro 
		name="default_cylinder_inertial" 
		params="mass length radius x_offset y_offset z_offset">
		<inertial>
			<origin xyz="${x_offset} ${y_offset} ${z_offset}" rpy="0 0 0"/>
			<mass value="${mass}"/>
			<inertia 
				ixx="1.0" ixy="0.0" ixz="0.0" 
				iyy="1.0" iyz="0.0" 
				izz="1.0"/>
		</inertial>
	</xacro:macro>
	
	<!-- import Rviz color -->
	<xacro:include filename="$(find camera_velodyne_calibration_gazebo)/materials/materials.xacro"/>

	<!-- import all Gazebo-customization elements, including Gazebo colors -->
	<xacro:include filename="$(find camera_velodyne_calibration_gazebo)/urdf/camera_velodyne.gazebo.xacro"/>

	
	<link name="world"/>

	<joint name="fixed" type="fixed">
		<parent link="world"/>
		<child link="base_link"/>
		<origin xyz="0 0 0" rpy="0 0 0"/>
	</joint>
	
	<!-- camera velodyne model  -->
	<link name="base_link"/>

	<joint name="base2velodyne_base" type="fixed">
		<parent link="base_link"/>
		<child link="velodyne_base_link"/>
		<origin xyz="0 0 ${velodyne_height - (velodyne_base_length + (velodyne_top_center + (velodyne_laser_height/2)))}" rpy="0 0 0"/>
	</joint>
	
	<!-- velodyne -->
	<link name="velodyne_base_link">
		<visual>
			<geometry>
				<cylinder length="${velodyne_base_length}" radius="${velodyne_diameter/2}"/>
			</geometry>
			<origin xyz="0 0 ${velodyne_base_length/2}" rpy="0 0 0"/>
			<material name="darkgray"/>
		</visual>
		<collision>
			<geometry>
				<cylinder length="${velodyne_base_length}" radius="${velodyne_diameter/2}"/>
			</geometry>
			<origin xyz="0 0 ${velodyne_base_length/2}" rpy="0 0 0"/>
		</collision>
		<xacro:default_cylinder_inertial 
			mass="1.0" length="${velodyne_base_length}" radius="${velodyne_diameter/2}"
			x_offset="0.0" y_offset="0.0" z_offset="${velodyne_base_length/2}"/>
	</link>

	<joint name="velodyne_top_joint" type="continuous">
		<parent link="velodyne_base_link"/>
		<child link="velodyne_top_link"/>
		<origin xyz="0 0 ${velodyne_base_length}" rpy="0 0 0"/>
		<axis xyz="0 0 1"/>
	</joint>

	<link name="velodyne_top_link">
		<visual>
			<geometry>
				<mesh filename="package://camera_velodyne_calibration_gazebo/meshes/velodyne_top.dae"/>
			</geometry>
			<origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
		</visual>
		<collision>
			<geometry>
				<cylinder length="${velodyne_top_length}" radius="${velodyne_diameter/2}"/>
			</geometry>
			<origin xyz="0 0 ${velodyne_top_length/2}" rpy="0 0 0"/>
		</collision>
		<xacro:default_cylinder_inertial 
			mass="0.0001" length="${velodyne_top_length}" radius="${velodyne_diameter/2}"
			x_offset="0.0" y_offset="0.0" z_offset="${velodyne_top_length/2}"/>
	</link>

	<joint name="velodyne_laser_joint" type="fixed">
		<parent link="velodyne_top_link"/>
		<child link="velodyne_laser_link"/>
		<origin xyz="0 0 ${(velodyne_top_center)+(velodyne_laser_height/2)}" rpy="0 0 0"/>
	</joint>
	
	<link name="velodyne_laser_link">
		<visual>
			<geometry>
				<box size="${velodyne_laser_depth} ${velodyne_laser_width} ${velodyne_laser_height}"/>
			</geometry>
			<origin xyz="${velodyne_laser_depth/2} 0 0" rpy="0 0 0"/>
			<material name="lase_black"/>
		</visual>
		<collision>
			<geometry>
				<box size="${velodyne_laser_depth} ${velodyne_laser_width} ${velodyne_laser_height}"/>
			</geometry>
			<origin xyz="${velodyne_laser_depth/2} 0 0" rpy="0 0 0"/>
		</collision>
		<xacro:default_box_inertial
			mass="0.0001" 
			depth="${velodyne_laser_depth}" 
			width="${velodyne_laser_width}" 
			height="${velodyne_laser_height}"
			x_offset="${velodyne_laser_depth/2}"
			y_offset="0.0"
			z_offset="0.0"/>
	</link>

	<joint name="velodyne_base2velodyne_laser_core" type="fixed">
		<parent link="velodyne_base_link"/>
		<child link="velodyne_laser_core_link"/>
		<origin xyz="0 0 ${velodyne_base_length + (velodyne_top_center + (velodyne_laser_height/2))}" rpy="0 0 0"/>
	</joint>

	<link name="velodyne_laser_core_link"/>
	
	<!-- monocular camera -->
	<joint name="base2camera" type="fixed">
		<parent link="base_link"/>
		<child link="camera_base_link"/>
		<origin xyz="${camera_depth} 0.015 ${camera_height}" rpy="0 0 0"/>
	</joint>

	<link name="camera_base_link">
		<visual>
			<geometry>
				<box size="0.020 0.070 0.030"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<material name="darkgray"/>
		</visual>
		<xacro:default_box_inertial
			mass="0.01" 
			depth="0.020" 
			width="0.070" 
			height="0.030"
			x_offset="0.0"
			y_offset="0.0"
			z_offset="0.0"/>
	</link>

	<joint name="camera_base2lens" type="fixed">
		<parent link="camera_base_link"/>
		<child link="lens_link"/>
		<origin xyz="0 -0.015 0" rpy="0 0 0"/>
	</joint>

	<link name="lens_link">
		<visual>
			<geometry>
				<cylinder length="0.017" radius="0.010"/>
			</geometry>
			<origin xyz="0.005 0 0" rpy="0 ${pi/2} 0"/>
			<material name="laser_black"/>
		</visual>
		<xacro:default_cylinder_inertial 
			mass="0.0001" length="0.017" radius="0.010"
			x_offset="0.005" y_offset="0.0" z_offset="0.0"/>
	</link>

	<!-- landmark  -->
	<joint name="base2landmark" type="fixed">
		<parent link="base_link"/>
		<child link="landmark_link"/>
		<origin xyz="2.5 0 ${camera_height}" rpy="0 0 0"/>
	</joint>

	<link name="landmark_link">
		<visual>
			<geometry>
				<mesh filename="package://camera_velodyne_calibration_gazebo/meshes/landmark.dae"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
		</visual>
		<collision>
			<geometry>
				<mesh filename="package://camera_velodyne_calibration_gazebo/meshes/landmark.dae"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
		</collision>
		<xacro:default_box_inertial
			mass="1.0" 
			depth="0.010" 
			width="1.000" 
			height="1.000"
			x_offset="0.0"
			y_offset="0.0"
			z_offset="0.0"/>
	</link>

	<transmission name="velodyne_top_trans">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="velodyne_top_joint">
			<hardwareInterface>VelocityJointInterface</hardwareInterface>
		</joint>
		<actuator name="velodyne_top_motor">
			<hardwareInterface>VelocityJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

</robot>

